---
title: "Word Prediction Application"
author: "Sandheep Sebastian"
date: "November 25, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Summary
This app predicts the next word of a sentence. The prediction algorithm was compiled by going though large amount of twitter, blogs and news text corpus and gathering information about various word fomation and relationships.This application serves as the final capstone project for the Data Specialiation course.
N gram methodology was used to identify word relationships to construct single word frequencies, two word frequencies and three word frequencies and stored in dataframes.Katz's Backoff algorithm was used to predict the probabilities of each of terms in dataframe, In case of unseen observations, the algorithm backed off from the current model to a lower model to pick the highest probable word that could complete the sentence entered. 

## Usage
Enter a sentence in the text box. Select the number of words to predict and click the 'Predict' Button. The app produces the highest probably next word in the sentence. The app also charts the probability of the top n words selected from the drop down menu, that could complete the sentence.

##References
The underlying data on which the processing and finally the algorithm was developed can be found in [Capstone Dataset](https://d396qusza40orc.cloudfront.net/dsscapstone/dataset/Coursera-SwiftKey.zip)
